sudo: required

language: python

notifications:
  email: false

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

install:
  - pip install -U pip
  - pip install pip-tools
  - pip-compile --output-file requirements.txt requirements.in
  - pip install -r requirements.txt

script:
  - travis_wait 60 pytest -vv tests
