sudo: required

language: python

notifications:
  email: false

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

before_install:
  - git clone https://github.com/ethereum/serpent
  - cd serpent && make && sudo make install && sudo python setup.py install && cd ..

install:
  - pip install -U pip
  - pip install -r test_requirements.txt

script:
  - travis_wait 60 py.test -s tests/runtests.py
