language: python
notifications:
  email: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - ./runtests.sh
