sudo: true

language: python

notifications:
  email: false

python:
  - "2.7"

before_install:
  - "export DEBIAN_FRONTEND=noninteractive"
  - sudo apt-get update -qq
  - sudo apt-get install python-gmpy2 python-numpy python-scipy -y -qq

install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"

script:
  - ./runtests.sh
