language: python

notifications:
  email: false

python:
  - "2.7_with_system_site_packages"

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - py.test tests/trading_tests.py
