language: python

notifications:
  email: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

install:
  - pip install -U pip
  - pip install pip-tools
  - pip install -r requirements.txt

script:
  - travis_wait 60 pytest -vv tests
