dist: trusty
sudo: false

cache:
  - apt
  - pip

language: python

notifications:
  email: false

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt

script:
  - travis_wait 60 pytest -vv tests
