sudo: true
language: python
notifications:
  email: false
python:
  - "2.7"
install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -y -qq
  - sudo apt-get install build-essential python-gmpy2 python-numpy python-matplotlib python-scipy -y -qq
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - ./runtests.sh
